### **Assignment: Understanding Data Preprocessing**

#### **Objective :**
In this assignment, you will learn how to analyze a dataset and determine the appropriate preprocessing technique for each feature before writing any preprocessing code (let's stick to tabular data for now).

In [7]:
# don't touch this code
import pandas as pd

df = pd.DataFrame({
    "Age":[18,22,25,28,30,35,40,45,50,55],

    "Salary":[25000,28000,32000,35000,42000,
              48000,55000,65000,72000,500000],

    "Experience":[0,1,2,3,5,7,10,12,15,20],

    "Gender":[
        "Male","Female","Male","Female","Male",
        "Female","Male","Female","Male","Female"
    ],

    "Education":[
        "High School","Bachelor","Bachelor",
        "Master","Master","PhD",
        "Bachelor","Master","PhD","PhD"
    ],

    "City":[
        "Hyderabad","Delhi","Mumbai","Delhi",
        "Hyderabad","Chennai","Mumbai",
        "Delhi","Hyderabad","Chennai"
    ]
})
df

   Age  Salary  Experience  Gender    Education       City
0   18   25000           0    Male  High School  Hyderabad
1   22   28000           1  Female     Bachelor      Delhi
2   25   32000           2    Male     Bachelor     Mumbai
3   28   35000           3  Female       Master      Delhi
4   30   42000           5    Male       Master  Hyderabad
5   35   48000           7  Female          PhD    Chennai
6   40   55000          10    Male     Bachelor     Mumbai
7   45   65000          12  Female       Master      Delhi
8   50   72000          15    Male          PhD  Hyderabad
9   55  500000          20  Female          PhD    Chennai

### **Step 1 Explore the Dataset**

Before performing any preprocessing, explore the dataset.

Complete the following tasks:

1) Display the first five rows.
2) Display the last five rows.
3) Display the shape of the dataset.
4) Display the data types of every column.

In [8]:
# write your code for step1 here
# Display the first five rows.
print(df.head())

   Age  Salary  Experience  Gender    Education       City
0   18   25000           0    Male  High School  Hyderabad
1   22   28000           1  Female     Bachelor      Delhi
2   25   32000           2    Male     Bachelor     Mumbai
3   28   35000           3  Female       Master      Delhi
4   30   42000           5    Male       Master  Hyderabad

In [9]:
# Display the last five rows.
df.tail()

   Age  Salary  Experience  Gender Education       City
5   35   48000           7  Female       PhD    Chennai
6   40   55000          10    Male  Bachelor     Mumbai
7   45   65000          12  Female    Master      Delhi
8   50   72000          15    Male       PhD  Hyderabad
9   55  500000          20  Female       PhD    Chennai

In [10]:
# Shape of DataSet
df.shape

(10, 6)

In [11]:
# DataTypes of Each Column
for col in df.columns:
  print(col,'->',df[col].dtype)

Age -> int64
Salary -> int64
Experience -> int64
Gender -> object
Education -> object
City -> object

### **Step 2 Understand the Features**

Now carefully analyze the dataset and answer the following questions.

1) How many numerical features are present?

2) How many categorical features are present?

3) Which feature contains the largest numerical values?

4) Do all numerical features have the same range?

5) Why could different feature scales become a problem for certain Machine Learning algorithms?

In [12]:
# How many numerical features are present?
print((df.select_dtypes(include='number')).columns)

print('Length :',len((df.select_dtypes(include='number')).columns))

Index(['Age', 'Salary', 'Experience'], dtype='object')
Length : 3

In [13]:
# How many categorical features are present?
print((df.select_dtypes(include='object')).columns)
print("Length :",len(df.select_dtypes(include='object').columns))

Index(['Gender', 'Education', 'City'], dtype='object')
Length : 3

In [14]:
# Which feature contains the largest numerical values?
df.select_dtypes(include='number').max()

# Analysis:
  # Salary feature has Largest values.

Age               55
Salary        500000
Experience        20
dtype: int64

In [15]:
# Do all numerical features have the same range?
numeric_df = df.select_dtypes(include='number')
numeric_df.max() - numeric_df.min()

# Analysis : No,The numerical features doe not have the same range

Age               37
Salary        475000
Experience        20
dtype: int64

##### 5. Why could different feature scales become a problem for certain Machine Learning algorithms?

- Features with much larger values can dominate those with smaller values, leading to poor model performance.

### **Step 3 Identify Feature Types**

Separate the dataset into

1) Numerical Features
2) Categorical Features

Then answer the following.


1) Which numerical feature has the largest range?

2) Which numerical feature appears to contain an outlier?

3) Which categorical feature is Binary?

4) Which categorical feature is Ordinal?

5) Which categorical feature is Nominal?

In [16]:
# write your code here for step-3
numerical=df.select_dtypes(include='number')
categorical = df.select_dtypes(include='object')

In [17]:
# Which numerical feature has the largest range?

(numerical.max()-numerical.min()).idxmax()

'Salary'

In [18]:
from numpy import quantile
# Which numerical feature appears to contain an outlier?
for col in numerical:
  q1=numerical[col].quantile(0.25)
  q3=numerical[col].quantile(0.75)
  iqr=q3-q1
  upperlimit=q3+1.5*iqr
  lowerlimit=q1-1.5*iqr
  outliers = numerical[
        (numerical[col] < lowerlimit) |
        (numerical[col] > upperlimit)
    ]
  if len(outliers)>0:
    print(col,'Contains Outliers')

Salary Contains Outliers

In [19]:
# Which categorical feature is Binary?
for col in categorical:
  if categorical[col].nunique()==2:
    print(col)

Gender

In [20]:
# Which categorical feature is Ordinal?
for col in categorical:
  print(col,':',categorical[col].unique())

# "Education is Ordinal because it is Ordered"

Gender : ['Male' 'Female']
Education : ['High School' 'Bachelor' 'Master' 'PhD']
City : ['Hyderabad' 'Delhi' 'Mumbai' 'Chennai']

In [21]:
# Which categorical feature is Nominal?
for col in categorical:
  print(col,':',categorical[col].unique())

# "City is Nominal because it does not have any Order"

Gender : ['Male' 'Female']
Education : ['High School' 'Bachelor' 'Master' 'PhD']
City : ['Hyderabad' 'Delhi' 'Mumbai' 'Chennai']

### **Step 4 Choosing the Correct Preprocessing Technique**

Without writing any preprocessing code, decide which preprocessing technique should be applied to every feature.

----------------------------------------------------------------------
#####Complete the below table dataframe in the next code cell and enter the correct preprocessing technique and justification in the "" string
----------------------------------------------------------------------

In [22]:
table = pd.DataFrame({
    "Column": ["Age", "Salary", "Experience", "Gender", "Education", "City"],
    "Feature Type": ["Numerical", "Numerical", "Numerical", "Binary", "Ordinal", "Nominal"],
    "Selected_Preprocessing_Technique": ["StandardScaler", "RobustScalar", "StandardScaler", "LabelEncoding", "OrdinalEncoding", "OneHotEncoding"],
    "Justification": ["Continuous numerical feature", "Salary contains outliers", "Continuous numerical feature", "Two categorical variables", "the categories have natural order", "caterogies have no order"]
})

table

,Column,Feature Type,Selected_Preprocessing_Technique,Justification
0,Age,Numerical,StandardScaler,Continuous numerical feature
1,Salary,Numerical,RobustScalar,Salary contains outliers
2,Experience,Numerical,StandardScaler,Continuous numerical feature
3,Gender,Binary,LabelEncoding,Two categorical variables
4,Education,Ordinal,OrdinalEncoding,the categories have natural order
5,City,Nominal,OneHotEncoding,caterogies have no order

### **Step 5  StandardScaler**

Read the official [documentation](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html) for StandardScaler.

Before writing any code, answer the following questions:
1) Why do we need StandardScaler?
- Standardize features by removing the mean and scaling to unit variance.
2) Which columns should be standardized?
- Columns which do not have Outliers, because standardization is senstive to outliers and can scale differently from each other in the presence of outliers.
3) What do you think StandardScaler learns during fit()?
- Compute the mean and std to be used for later scaling.
4) Which attributes do you expect to see after fitting?
- mean_
- var_
- scale_
- n_features_in_

#### write your answers for step-5 here

### **Step 6  Apply standard scaler to the features for which standardization is required**

1) Create the scaler.

In [25]:
# code here
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
scalar

StandardScaler()

2) Fit the scaler only on the feature(s) you selected.

In [26]:
# code here
scaled=scalar.fit(df[['Age']])

3) What do you think this scaler has learned during fit()?

In [28]:
# code here
# print scaler.mean_
#print scaler.scale_
print(scaled.mean_)
print(scaled.scale_)
# Compute the mean and std to be used for later scaling.

[34.8]
[11.7541482]

4) Use the scaler.fit_transform and scaler.transform, What did you observe?

In [30]:
# code here
fit_transform=scalar.fit_transform(df[['Age']])
transform=scalar.transform(df[['Age']])
print(fit_transform)
print(transform)

# No Differencev in the result,because:

# fit():
  # Calculates the mean and standard deviation of the Age column.
#transform()
  # Uses those values to standardize the data.

[[-1.42928264]
 [-1.08897725]
 [-0.83374821]
 [-0.57851916]
 [-0.40836647]
 [ 0.01701527]
 [ 0.44239701]
 [ 0.86777875]
 [ 1.29316049]
 [ 1.71854222]]
[[-1.42928264]
 [-1.08897725]
 [-0.83374821]
 [-0.57851916]
 [-0.40836647]
 [ 0.01701527]
 [ 0.44239701]
 [ 0.86777875]
 [ 1.29316049]
 [ 1.71854222]]

In [31]:
df

   Age  Salary  Experience  Gender    Education       City
0   18   25000           0    Male  High School  Hyderabad
1   22   28000           1  Female     Bachelor      Delhi
2   25   32000           2    Male     Bachelor     Mumbai
3   28   35000           3  Female       Master      Delhi
4   30   42000           5    Male       Master  Hyderabad
5   35   48000           7  Female          PhD    Chennai
6   40   55000          10    Male     Bachelor     Mumbai
7   45   65000          12  Female       Master      Delhi
8   50   72000          15    Male          PhD  Hyderabad
9   55  500000          20  Female          PhD    Chennai

### **Step 8  Apply MinMax and Robust scaler to the features for which they are required**

In [32]:
scaled=scalar.fit_transform(df[['Experience']])
scaled

array([[-1.19409192],
       [-1.03487966],
       [-0.87566741],
       [-0.71645515],
       [-0.39803064],
       [-0.07960613],
       [ 0.39803064],
       [ 0.71645515],
       [ 1.19409192],
       [ 1.9901532 ]])

In [33]:
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()

scaled_data = scaler.fit_transform(df[['Salary']])
scaled_data

array([[-0.67226891],
       [-0.57142857],
       [-0.43697479],
       [-0.33613445],
       [-0.10084034],
       [ 0.10084034],
       [ 0.33613445],
       [ 0.67226891],
       [ 0.90756303],
       [15.29411765]])

### **Step 9 Fit a LabelEncoder on the columns where they are required?**

Read the [documentation](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html).

1) Why is LabelEncoder suitable for the Gender column?
- LabelEncoder is suitable because Gender is a binary categorical feature (e.g., Male/Female). Since there are only two categories, converting them into numerical values such as 0 and 1 is sufficient.
2) What do you think LabelEncoder learns during fit()?
- Finds all the unique categories.
- Sorts them .
- Assigns each category a unique integer.
3) Which attribute should contain the learned information?
- The learned categories are stored in the classes_ attribute.

1) fit the encoder

In [34]:
# code here
# check encoder.classes_
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

encoder.fit(df["Gender"])

print(encoder.classes_)

['Female' 'Male']

2) transform the features

In [35]:
# code here
# after that use encoder.inverse_transform
encoded = encoder.transform(df["Gender"])
print(encoded)
original = encoder.inverse_transform(encoded)
print(original)

[1 0 1 0 1 0 1 0 1 0]
['Male' 'Female' 'Male' 'Female' 'Male' 'Female' 'Male' 'Female' 'Male'
 'Female']

3) Use fit_transform

In [36]:
# code here
# what did you observe?
encoder = LabelEncoder()

encoded = encoder.fit_transform(df["Gender"])

print(encoded)
print(encoder.classes_)

[1 0 1 0 1 0 1 0 1 0]
['Female' 'Male']

- fit() learns the unique categories.
- transform() converts categories into numbers.
- fit_transform() performs both operations in one step.
- inverse_transform() converts the encoded values back to the original categories.

### **Step 9 Then repeat the same workflow for OrdinalEncoder on columns where it is required**
Go through the documentation yourself

In [39]:
from sklearn.preprocessing import OrdinalEncoder

encoder=OrdinalEncoder()
encoded=encoder.fit_transform(df[['Education']])
print(encoded)

[[1.]
 [0.]
 [0.]
 [2.]
 [2.]
 [3.]
 [0.]
 [2.]
 [3.]
 [3.]]

### **Step 10 Now repeat the same workflow for OneHotEncoder on columns where it is required**

In [41]:
# code here
# after fitting the encoder check encoder.categories_
# check encoder.get_feature_names_out()

from sklearn.preprocessing import OneHotEncoder

encoder=OneHotEncoder()
encoded=encoder.fit_transform(df[['City']])
features=encoder.get_feature_names_out()
print(features)
print(encoded)

['City_Chennai' 'City_Delhi' 'City_Hyderabad' 'City_Mumbai']
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10 stored elements and shape (10, 4)>
  Coords	Values
  (0, 2)	1.0
  (1, 1)	1.0
  (2, 3)	1.0
  (3, 1)	1.0
  (4, 2)	1.0
  (5, 0)	1.0
  (6, 3)	1.0
  (7, 1)	1.0
  (8, 2)	1.0
  (9, 0)	1.0

### **Final Step, Now that you understand every preprocessing technique individually**

1) build a single preprocessing pipeline.

2) Finally, combine them using ColumnTransformer, refer to    [documentation](https://scikit-learn.org/stable/modules/generated/sklearn.compose.ColumnTransformer.html) and transform the complete dataset.

In [42]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import (
    StandardScaler,
    OneHotEncoder,
    OrdinalEncoder
)

num_cols = ["Age", "Salary","Experience"]
ordinal_cols = ["Education"]
nominal_cols = ["City"]
binary_cols = ["Gender"]

num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

ordinal_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OrdinalEncoder(categories=[
        ["High School", "Bachelor", "Master", "PhD"]
    ]))
])

nominal_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

binary_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OrdinalEncoder())
])

preprocessor = ColumnTransformer([
    ("num", num_pipeline, num_cols),
    ("ordinal", ordinal_pipeline, ordinal_cols),
    ("nominal", nominal_pipeline, nominal_cols),
    ("binary", binary_pipeline, binary_cols)
])

X_processed = preprocessor.fit_transform(df)

print(X_processed)

[[-1.42928264 -0.47451185 -1.19409192  0.          0.          0.
   1.          0.          1.        ]
 [-1.08897725 -0.45267848 -1.03487966  1.          0.          1.
   0.          0.          0.        ]
 [-0.83374821 -0.42356732 -0.87566741  1.          0.          0.
   0.          1.          1.        ]
 [-0.57851916 -0.40173396 -0.71645515  2.          0.          1.
   0.          0.          0.        ]
 [-0.40836647 -0.35078943 -0.39803064  2.          0.          0.
   1.          0.          1.        ]
 [ 0.01701527 -0.3071227  -0.07960613  3.          1.          0.
   0.          0.          0.        ]
 [ 0.44239701 -0.25617818  0.39803064  1.          0.          0.
   0.          1.          1.        ]
 [ 0.86777875 -0.18340028  0.71645515  2.          0.          1.
   0.          0.          0.        ]
 [ 1.29316049 -0.13245576  1.19409192  3.          0.          0.
   1.          0.          1.        ]
 [ 1.71854222  2.98243797  1.9901532   3.          1.          0.
   0.          0.          0.        ]]